"""Build a Markdown index for INCUBATOR tuple documents."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.parse_chat_tuple import ROOT, load_tuple_documents

DEFAULT_OUTPUT = ROOT / "docs" / "incubator_index.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to write the generated markdown index.",
    )
    return parser.parse_args()


def build_markdown() -> str:
    docs = sorted(load_tuple_documents(), key=lambda item: item["id"])
    lines = [
        "# Incubator Index",
        "",
        "Machine-readable tuple ingress index (W001 scaffold).",
        "",
        "| ID | Date | Time | Category | Theme | Title | Wave | Status | Source |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in docs:
        lines.append(
            "| {id} | {date} | {time_local} | {category} | {theme} | {title} | {wave} | {status} | {source} |".format(
                id=item["id"],
                date=item["date"],
                time_local=item["time_local"],
                category=item["category"],
                theme=item["theme"],
                title=item["title"],
                wave=item["wave"],
                status=item["status"],
                source=item["_file"],
            )
        )
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Naming: `YY_Www_HH_MM__CATEGORY__THEME__TITLE__STATUS`.",
            "- Generated by `python scripts/build_incubator_index.py`.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    markdown = build_markdown()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
